---
# Role tasks

- name: Configure allowed services
  when: tcpwrappers_allow is defined
  lineinfile:
    name: /etc/hosts.allow
    backup: yes
    state: "{{ hosts_entry.state }}"
    line: "{{ hosts_entry.daemons | join(',') }}:{{
              hosts_entry.clients | join(',') }}:{{
              hosts_entry.options | default([]) | join(':') }}"
  loop: "{{ tcpwrappers_allow }}"
  loop_control:
      loop_var: hosts_entry

- name: Configure denied services
  when: tcpwrappers_deny is defined
  lineinfile:
    name: /etc/hosts.deny
    backup: yes
    state: "{{ hosts_entry.state }}"
    line: "{{ hosts_entry.daemons | join(',') }}:{{
              hosts_entry.clients | join(',') }}:{{
              hosts_entry.options | default([]) | join(':') }}"
  loop: "{{ tcpwrappers_deny }}"
  loop_control:
      loop_var: hosts_entry
