---
# Role tasks

- block:
    - name: Configure allowed services
      lineinfile:
        name: /etc/hosts.allow
        backup: yes
        state: "{{ tcpwrappers_line.state }}"
        line: "{{ tcpwrappers_line.content }}"
        create: yes
        owner: root
        group: root
        mode: 0644
      when: tcpwrappers_allow is defined
      loop: "{{ lookup('template', 'lines.yml.j2') | from_yaml }}"
      loop_control:
        loop_var: tcpwrappers_line
        label: "{{ tcpwrappers_line.content }}"
      vars:
        tcpwrappers_to_manage: >-
          {{ tcpwrappers_allow
             + ((tcpwrappers_load_from_hostvars)
                | ternary(tcpwrappers_allow_hostvars
                          | default([])
                          | flatten,
                          [])) }}
      tags:
        - role::tcpwrappers::allow

    - name: Configure denied services
      lineinfile:
        name: /etc/hosts.deny
        backup: yes
        state: "{{ tcpwrappers_line.state }}"
        line: "{{ tcpwrappers_line }}"
        create: yes
        owner: root
        group: root
        mode: 0644
      when: tcpwrappers_allow is defined
      loop: "{{ lookup('template', 'lines.yml.j2') | from_yaml }}"
      loop_control:
        loop_var: tcpwrappers_line
        label: "{{ tcpwrappers_line.content }}"
      vars:
        tcpwrappers_to_manage: >-
          {{ tcpwrappers_deny
             + ((tcpwrappers_load_from_hostvars)
                | ternary(tcpwrappers_deny_hostvars
                          | default([])
                          | flatten,
                          [])) }}
      tags:
        - role::tcpwrappers::deny
  tags:
    - role::tcpwrappers
