---
# Role tasks

- block:
    - name: Configure allowed services
      lineinfile:
        name: /etc/hosts.allow
        backup: yes
        state: "{{ hosts_entry.state }}"
        line: "{{ tcpwrappers_line }}"
        create: yes
        owner: root
        group: root
        mode: 0644
      when: tcpwrappers_allow is defined
      loop: "{{ tcpwrappers_to_manage }}"
      loop_control:
        loop_var: hosts_entry
        label: "{{ tcpwrappers_line }}"
      vars:
        tcpwrappers_to_manage: >-
          {{ tcpwrappers_allow
             + ((tcpwrappers_load_from_hostvars)
                | ternary(tcpwrappers_allow_hostvars
                          | default([])
                          | flatten,
                          [])) }}
      tags:
        - role::tcpwrappers::allow

    - name: Configure denied services
      lineinfile:
        name: /etc/hosts.deny
        backup: yes
        state: "{{ hosts_entry.state }}"
        line: "{{ tcpwrappers_line }}"
        create: yes
        owner: root
        group: root
        mode: 0644
      when: tcpwrappers_deny is defined
      loop: "{{ tcpwrappers_to_manage }}"
      loop_control:
        loop_var: hosts_entry
        label: "{{ tcpwrappers_line }}"
      vars:
        tcpwrappers_to_manage: >-
          {{ tcpwrappers_deny
             + ((tcpwrappers_load_from_hostvars)
                | ternary(tcpwrappers_deny_hostvars
                          | default([])
                          | flatten,
                          [])) }}
      tags:
        - role::tcpwrappers::deny
  vars:
    tcpwrappers_line: >-
      {{ hosts_entry.daemons | join(',')
         + ":"
         + hosts_entry.clients | join(',')
         + (hosts_entry.options | default([]) | length > 0) | ternary(":", "")
         + hosts_entry.options | default([]) | join(':') }}
  tags:
    - role::tcpwrappers
